import * as z from 'zod'

export const CreateServiceOrderDTO = z.object({
  code: z.string().optional(),
  observation: z.string().optional(),
  organization: z.string(),
  customer: z.string(),
  member: z.string().optional(),
  originZipCode: z.string().length(8).optional(),
  originComplement: z.string().optional(),
  originLatitude: z.coerce.number().optional(),
  originLongitude: z.coerce.number().optional(),
  destinationZipCode: z.string().length(8).optional(),
  destinationComplement: z.string().optional(),
  destinationLatitude: z.coerce.number().optional(),
  destinationLongitude: z.coerce.number().optional(),
  deadline: z.coerce.date().optional(),
  started: z.boolean().optional(),
  startDate: z.coerce.date().optional(),
  startNote: z.string().optional(),
  completed: z.boolean().optional(),
  completionDate: z.coerce.date().optional(),
  completionNote: z.string().optional(),
  canceled: z.boolean().optional(),
  cancellationDate: z.coerce.date().optional(),
  cancellationNote: z.string().optional(),
})
export type CreateServiceOrderDTOType = z.infer<typeof CreateServiceOrderDTO>

export const UpdateServiceOrderDTO = z.object({
  code: z.string().optional().optional(),
  observation: z.string().optional(),
  organization: z.string().optional(),
  customer: z.string().optional(),
  member: z.string().optional(),
  originZipCode: z.string().length(8).optional(),
  originComplement: z.string().optional(),
  originLatitude: z.coerce.number().optional(),
  originLongitude: z.coerce.number().optional(),
  destinationZipCode: z.string().length(8).optional(),
  destinationComplement: z.string().optional(),
  destinationLatitude: z.coerce.number().optional(),
  destinationLongitude: z.coerce.number().optional(),
  deadline: z.coerce.date().optional(),
  started: z.boolean().optional(),
  startDate: z.coerce.date().optional(),
  startNote: z.string().optional(),
  completed: z.boolean().optional(),
  completionDate: z.coerce.date().optional(),
  completionNote: z.string().optional(),
  canceled: z.boolean().optional(),
  cancellationDate: z.coerce.date().optional(),
  cancellationNote: z.string().optional(),
})
export type UpdateServiceOrderDTOType = z.infer<typeof UpdateServiceOrderDTO>
